# Generated by Django 5.2 on 2025-05-19 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0002_studentprofile_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='E.g., Computer Science', max_length=100)),
                ('reg_no_prefix', models.CharField(help_text='Static prefix (e.g., U18UZ22S)', max_length=20)),
                ('start_range', models.IntegerField(help_text='Starting number (e.g., 1)')),
                ('end_range', models.IntegerField(help_text='Ending number (e.g., 115)')),
            ],
        ),
    ]
