# Generated by Django 5.2 on 2025-05-23 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0003_department'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
    ]
